### ISSUE TITLE
Logout not working in IE11

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#54]
If I'm logged in with a user and make a request to `api/logout`, the request is successful (200, OK), but when I reload the page the user is still logged in. I have to delete cookies manually to log out.

Domain: hsb-test-carbon.meshify.com
Browser: IE11

**Comment by Ashtonian** [comment]
should be working now, sorry for the delay, let me know if there are any additional issues.

**Comment by balintd** [comment]
Thank you!

**Comment by balintd** [comment]
Unfortunately it still doesn't seem to be working. I log in with User A in IE11, log out, then log in with User B, I still get logged in as User A.

I usually notice this while working on the Enrollment core, but I also noticed, in IE11 the Admin core Log Out button doesn't work either. I click Log Out then I get redirected back to the same page, logged in as the same user. The two issues might be related.

**Comment by Ashtonian** [comment]
Does it happen every time ? which environment are you pointing to?

**Comment by decker405** [comment]
@Ashtonian there are possibly issues with IE, cookies, and `localhost`

**Comment by balintd** [comment]
Yes, it seems to happen every time. My first example can be checked here https://hsbqa.carbon.meshify.com/enrollment

I log in with one user, log out, log back in with another, I'm still being logged in as the previous user. It happens both on my local environment and at hsbqa.carbon.meshify.com.

**Comment by Ashtonian** [comment]
IE caches all get ajax requests by default, so the front end is not hitting the api very often it would seem. This is evident in the network monitor for IE having 304 status code responses with <1ms response times. We need to set the `cache-control` header properly to tell IE how to behave. A PR has been submitted, hoping to deploy early next week. 

Additional info: 
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
https://stackoverflow.com/questions/5017454/make-ie-to-cache-resources-but-always-revalidate

**Comment by Ashtonian** [comment]
@balintd so good news and bad. So good news is we have deployed a fix using the cache-control header setting using the `"must-revalidate, private"`. The intent of this is to instruct browsers to send an ETag to the server always. This is deployed/working as far as the logout goes. Unfortunately IE is no longer using ETags, and I'm not sure why. This isn't that big of an issue as this is just a performance optimization. I've opened up another ticket to address that at a later point: https://github.com/meshifyiot/carbon-docs/issues/175. Let me know if you have any issues.

**Comment by balintd** [comment]
Unfortunately it still doesn't seem to work. I'm testing on hsbqa.carbon.meshify.com in IE11. Having the same issues I've described above.

**Comment by Ashtonian** [comment]
sorry try again, wrong version deployed

**Comment by balintd** [comment]
Awesome, thank you!
